---
title: 'EthicsNotes_course'
author: "Alex Gu, via RMarkdown"
date: "Last modified `r format(Sys.time(), '%x')`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---
[comment]:<>(Some comments.)
```{r Setup, include = FALSE}
knitr::opts_chunk$set(prompt = FALSE, comment = "", collapse = TRUE, echo = FALSE, warning = FALSE,error = FALSE, message = FALSE)

rm(list=ls())

```

# Course 1. Dec.5th, 2022

## Aims 
- Means 1: human subjects research
- Means 2: research integrity

## A group work
- The participant teaching session, 50min presentation including 15min discussion.

## A second group work, only on Thursday at the first week
- Ethics review exercise with someone in a different group from the first group work.

## Ethics reflection
- One identified issue regarding one's own research. Before 16pm next Thursday, submit at least two reflections of others' submission.
- Length: around 900 words

## Justify one's project
- No justification (of ethics?);
- (potential) instrumental value "impact": tangible, immediate; hard to predict; basic/foundational science value; 
- intrinsic/final value: 
...

# Course 2. Dec. 6th, 2022
Human subjects research

## What's at stake
- Harm and burden; from interview, survey, experiment, participant observation, analysis of personal data;
- Violations of privacy;
- Instrumentalization, exploitation; Or using people as means for others' ends;


## The relevance of consent
- Minize the risk;
- Consent makes many research acceptable;

# Course 3. Dec. 7th, 2022
Guidelines, legislation and ethical review
- GDPR
- Convention on human rights and biomedicine
- The Swedish Ethical Review Act
- Personal data? Any info to be able to identify a natural person (a live one); Coded data if there is still a key is also personal data; 
- pseudonymise (GDPR) is better; Avoid using the terms or explain what you mean by using these terms: anonymize ? De-identify? 
- sensitive personal data (GDPR) contain: race/ethnic, political opinion, religious, trade union membership, sex life and orientation, health, genetic inof, biometric info for unique identification of a person; If something does not fall into these categories, then it is not sensitive data.
- GPS data is sometimes sensitive, showing you are coming to a church. In most situations, it should be personal data.
- Ethics is required: if involved sensitive personal data; or personal data regarding some sort of violation of regulations; physical intervention; an attempt to somehow influence the participant (physically or mentally; obivious risk that participants will be harmed phyisically or mentally; If anything of biological material that has been taken form a person and can be traced to that person;
- The authority to do the ethical review: The Swedish Ethical Review Autority (EPM); Ethics Review Appeals Board will do some oversight on decided cases;
- Research cannot start before it has been reviewed and approved.
- No retroactive approval.
- People violating provisions will be subjected to CRIMINAL liability.
